name: Docker CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: Run Docker containers
        run: |
          docker compose -f docker-compose.yml up -d
        env:
          MONGO_URI: mongodb://mongo:27017

      - name: Wait for app to be healthy
        run: |
          sleep 10  # Replace with better healthcheck if needed
          curl --fail http://localhost || (docker compose logs && exit 1)

      - name: Stop containers
        run: docker compose down
